apiVersion: apps/v1
kind: Deployment
metadata:
  name: rental
  labels:
    app: rental
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rental
  template:
    metadata:
      labels:
        app: rental
      annotations:
        sidecar.istio.io/inject: "true"  
    spec:
      hosts:
      - rental
      http:
      - route:
        - destination:
            host: rental
      containers:
        - name: rental
          image: 467263215646.dkr.ecr.ap-northeast-1.amazonaws.com/skccuser17-rental:v1
          #username/Rental:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/rentals/'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/rentals/'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
